---
- name: Install and start Nginx service
  hosts: localhost # Fixed 'host' to 'hosts'

  tasks:
    - name: Install Nginx
      apt: # Added 'ansible.builtin' for clarity
        name: nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
